### ISSUE TITLE
results

### ISSUE THREAD

**Issue by arpit15** [itaicaspi/keras-dqn-doom#1]
I don't seem to be able to get results mentioned in this repos README.md with the simple dqn over doomSimple with training from 10k episodes. 
Please mention the hyperparameters used to obtain the results in this repos README.md

The following is the graph I obtain by training using only dqn for 10k episodes with hyperparameters provided in main.py last lstm variable
![av_q_10000epi](https://cloud.githubusercontent.com/assets/4703676/19907239/531d3500-a054-11e6-9557-834ac6653cb7.png)

**Comment by itaicaspi** [comment]
Change the runs array in line 1293 to [egreedy].
it should solve your issue. 
all the other hyper-parameters are set in the egreedy dictionary on line 1235.

**Comment by arpit15** [comment]
Just to confirm, to reproduce your results I am using the following hyperparameters.

egreedy = {
            "snapshot_episodes": 1000,
            "episodes": 10000,
            "steps_per_episode": 40, # 4300 for deathmatch, 300 for health gathering
            "average_over_num_episodes": 50,
            "start_learning_after": 20,
            "algorithm": Algorithm.DDQN,
            "discount": 0.99,
            "max_memory": 1000,
            "prioritized_experience": False,
            "exploration_policy": ExplorationPolicy.E_GREEDY,
            "learning_rate": 2.5e-4,
            "level": Level.BASIC,
            "combine_actions": True,
            "temperature": 10,
            "batch_size": 10,
            "history_length": 4,
            "snapshot": '',
            "mode": Mode.TRAIN,
            "skipped_frames": 4,
            "target_update_freq": 1000,
            "steps_between_train": 1,
            "epsilon_start": 0.5,
            "epsilon_end": 0.01,
            "epsilon_annealing_steps": 3e4,
            "architecture": Architecture.DIRECT,
            "max_action_sequence_length": 1
        }

I will post the results after the training is over. 
Did you experiment with target_update_freq and max_memory?

**Comment by itaicaspi** [comment]
yes, seems right.
I did a sweep over the target_update_freq and max_memory until I found the best values.
for max_memory - the larger the better, but it depends on how much memory you have.
most of the time I set it to 10k but 1k should be ok.

**Comment by arpit15** [comment]
Thank you. The implementation results are close to that shown in the README.md. 
![av_q_10k](https://cloud.githubusercontent.com/assets/4703676/19912686/a030f5f2-a072-11e6-83cf-dd1a394e9d2c.png)

**Comment by itaicaspi** [comment]
great :)
